### ISSUE TITLE
GitHub 라벨링 개선

### ISSUE THREAD

**Issue by solo5star** [woowacourse-teams/2023-yozm-cafe#101]
## 📑 논의 사항
> 이 이슈는 제안이므로 반영될 수도, 반영되지 않을 수도 있습니다.

<img height="500" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/4eb76db4-9c5a-4543-adb3-17d9f4f0c4c4">

GitHub 이슈 또는 PR을 작성할 때 사용하는 라벨들을 개선한다.

* 프론트엔드, 백엔드 라벨링 짧게 개선 (라인을 너무 많이 잡아먹음)
* 라벨링 정렬을 위해 prefix 붙이기 (`분야:FE`, `분야:BE`)
* 우선순위 라벨링하기 (색깔을 활용하여 강조)

## 🎸 기타사항

**Comment by donghae-kim** [comment]
전 라벨링에서 이모지를 제거해도 좋다고 생각합니다! 라인을 잡아먹는다기보다는 가독성이 조금 떨어지는 것 같아서 ㅠㅠ

정렬이 자동으로 된다면 prefix붙이는 것도 좋습니다~!!

**Comment by solo5star** [comment]
그쵸 약간 요런 느낌으로 참고하면 좋을 듯 하네요

<img height="700" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/fb28fc86-ec85-4800-a4ae-6982eb05256e">
