### ISSUE TITLE
GitHub 마일스톤 및 칸반 View 활용하기

### ISSUE THREAD

**Issue by solo5star** [woowacourse-teams/2023-yozm-cafe#102]
## 📑 논의 사항
> 제안이므로 반영될 수도, 반영되지 않을 수도 있습니다.

<img height="300" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/45e1469e-910c-4a39-b156-136f27fbab7f">

<img height="300" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/20203944/978db101-357a-413c-acdc-14d2b0f1db96">

현재 마일스톤 기능을 "2차 데모데이", "3차 데모데이" 등 스프린트 단위로 사용하고 있습니다.

지금처럼 큼직한 단위로 마일스톤을 만들기보다 좀 더 구체적인 작업 단위와 일정으로 마일스톤을 만드는 것에 대해 이야기해보면 좋을 것 같습니다.

지금까지 만들던 "2차 데모데이", "3차 데모데이"는 칸반에 View 단위로 만들어도 좋을 것 같습니다.

## 🎸 기타사항

혹여나 의견 있다면 자유롭게 말씀해주세요. 감사합니다.

**Comment by donghae-kim** [comment]
`지금처럼 큼직한 단위로 마일스톤을 만들기보다 좀 더 구체적인 작업 단위`라는게 어떤 정도일까요?
2차 데모데이의 로그인 기능 구현 이라는 마일스톤 하에 토큰받기, 갱신 등등 이런식으로 진행하는 것을 의미하는것인가요 !?

**Comment by solo5star** [comment]
네넵 맞습니다. 저희가 목표로 세운 `데이터 수집`, `좋아요 기능 구현` 같은 것이 좀 더 구체적인 단위가 될 듯 합니다.
