### ISSUE TITLE
배포 환경용 webpack config를 설정한다.

### ISSUE THREAD

**Issue by solo5star** [woowacourse-teams/2023-yozm-cafe#190]
## 📑 작업 사항
현재 webpack.config.js 에는 `mode: 'development'` 로 되어있어 빌드 후 실행해도 MSW가 동작하고 있다.
빌드 시엔 `mode: 'production'` 으로 설정되게 하여 MSW 비활성화 등 production 환경에 맞게 빌드되도록 한다.

## To-do
- [ ] webpack production용 config 작성하기

## 🎸 기타사항
* 공식 문서 가이드: https://webpack.js.org/guides/production/

**Comment by jeongwusi** [comment]
해당 이슈는 해결을 하였기 때문에 Close 하도록 하겠습니다.

참고: https://github.com/woowacourse-teams/2023-yozm-cafe/issues/191
