### ISSUE TITLE
[Bug] 무한 스크롤시

### ISSUE THREAD

**Issue by cpot5620** [woowacourse-teams/2023-yozm-cafe#290]
## 📑 작업 사항

> 작업할 내용을 작성해주세요

## 📝 에러 내용

> 에러 내용을 설명해주세요

## 👾 에러 원인

> 에러 원인을 설명해주세요
모든 카페를 조회한 경우,  더 이상 스크롤이 안 되요.
## 🎸 기타 사항

> 기타 사항을 작성해주세요

**Comment by geuntaek1013** [comment]
#294 해당 이슈와 중복이라 close 하겠습니다!!:)
