### ISSUE TITLE
[Bug] 스크롤 시 화면이 중간에 걸리는 문제가 있음

### ISSUE THREAD

**Issue by kpeel5839** [woowacourse-teams/2023-yozm-cafe#291]
## 📑 작업 사항

> 작업할 내용을 작성해주세요

스크롤

## 📝 에러 내용

> 에러 내용을 설명해주세요

카페 목록 스크롤 중에 아래와 같은 상황이 일어남

<img width="1440" alt="image" src="https://github.com/woowacourse-teams/2023-yozm-cafe/assets/89840550/cfb060d8-f867-403f-a20b-2a2b84411bef">

## 👾 에러 원인

> 에러 원인을 설명해주세요

수평으로 스크롤 하면 발생함

## 🎸 기타 사항

> 기타 사항을 작성해주세요

**Comment by geuntaek1013** [comment]
네, 해당 문제 해결하였습니다!!
