### ISSUE TITLE
[버그는 아니지만] 기타 사항 내용입니다.

### ISSUE THREAD

**Issue by hyena0608** [woowacourse-teams/2023-yozm-cafe#292]
## 📑 작업 사항

> 작업할 내용을 작성해주세요

- 굿 없습니다.

## 📝 에러 내용

> 에러 내용을 설명해주세요

- 굿 없습니다.

## 👾 에러 원인

> 에러 원인을 설명해주세요

- 굿 없습니다.

## 🎸 기타 사항

> 기타 사항을 작성해주세요

- 화면에서 왼쪽, 오른쪽 사진을 슬라이딩해서 볼 수 없습니다.
- 프로필에서 좋아요한 카페를 들어갈 수 없습니다. (또한 목록에 정보가 없어 사진을 보고 판단해야 합니다.)
- 더보기 버튼을 누른후 나온 창?을 아래로 드래그 할 때 자동으로 내려가면 빠르게 보기 편할거 같습니다.

**Comment by geuntaek1013** [comment]
네, 이번 스프린트에 구현 예정입니다.
