### ISSUE TITLE
[Bug] 빠르게 스크롤시 카페가 반복됩니다

### ISSUE THREAD

**Issue by cookienc** [woowacourse-teams/2023-yozm-cafe#293]
## 📑 작업 사항

> 맥북에서 웹 접속으로 빠르게 스크롤해서 카페를 내려봤습니다.

## 📝 에러 내용

> 천천히 스크롤하면 카페가 정상적으로 다른 카페가 나오는 것 같은데, 빠르게 스크롤하면 처음 나온 카페로 돌아가는 이슈가 있습니다.

## 👾 에러 원인

> 찾아주세요~

## 🎸 기타 사항

> 기타 사항을 작성해주세요

**Comment by geuntaek1013** [comment]
#294 해당 이슈와 중복이라 close 하겠습니다!!:)
