### ISSUE TITLE
[Bug] 약 5개 스크롤 시 마다 사진 버벅임 발생

### ISSUE THREAD

**Issue by yoondgu** [woowacourse-teams/2023-yozm-cafe#295]
## 📑 작업 사항

> 작업할 내용을 작성해주세요

## 📝 에러 내용

> 에러 내용을 설명해주세요

빠르게 스크롤하지 않아도(약 2초마다 1회), 5개 정도 스크롤하면 사진이 버벅이는 현상이 발생합니다.
(다른 사진이 잠깐 보이는 버벅임)

## 👾 에러 원인

> 에러 원인을 설명해주세요

## 🎸 기타 사항

> 기타 사항을 작성해주세요

**Comment by geuntaek1013** [comment]
#294 해당 이슈와 중복이라 close 하겠습니다!!:)
