### ISSUE TITLE
[버그는 아니지만] 좋아요 한 카페의 리스트를 확인하고, 다시 들어갈 수 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by eunbii0213** [woowacourse-teams/2023-yozm-cafe#296]
## 📑 작업 사항

> 작업할 내용을 작성해주세요

## 📝 에러 내용

> 에러 내용을 설명해주세요

좋아요 한 카페의 리스트를 확인하고, 다시 들어갈 수 있었으면 좋겠습니다.

## 👾 에러 원인

> 에러 원인을 설명해주세요

## 🎸 기타 사항

> 기타 사항을 작성해주세요

**Comment by geuntaek1013** [comment]
네, 이번 스프린트에 구현 예정입니다.
