### ISSUE TITLE
/cafes/{cafe_id}/history API deprecated 처리 혹은 삭제하기

### ISSUE THREAD

**Issue by hum02** [woowacourse-teams/2023-yozm-cafe#316]
## 📑 논의 사항
> 현재 시청 기록처리가 백엔드에서는 카페들을 응답하자마자 해당 unViewedCafe들을 지웁니다.
때문에 기존의 /cafes/{cafe_id}/history API는 필요가 없고 오히려 불필요한 요청을 보내 리소스를 낭비하고 있습니다.

백엔드에서 먼저 해당 API를 지우면 프론트 측에서는 아직 해당 API를 사용하기에 에러로그가 발생합니다.
때문에 프론트에서 먼저 API를 사용하지 않도록 코드를 변경 후, 백엔드에서도 해당 API를 지우도록 수정하기를 요청합니다.

**Comment by solo5star** [comment]
제가 issue link를 잘못해서 close되었네요 죄송합니다 ㅎㅎ;;;
