### ISSUE TITLE
`suspense: true`로 사용할 시 `useQuery`의 타입이 맞지 않는 문제 해결하기

### ISSUE THREAD

**Issue by solo5star** [woowacourse-teams/2023-yozm-cafe#35]
## 📑 논의 사항
```tsx
const Home = () => {
  const { data } = useQuery({
    queryKey: ['cafes'],
    queryFn: () => client.getCafes(),
  });
}
```
위 코드에서 `data` 의 타입은 `Cafe[] | undefined` 로 평가됩니다. 이는 `suspense: true`로 켜놓아도 동일하게 되는데, `suspense: true` 일때 `data` 는 `undefined`가 될 수 없습니다. 즉 `Cafe[]` 타입으로 되어야 합니다.

다른 프로젝트에서는 어떻게 해결하였는지 한번 찾아보았습니다.
* `useQuery`를 래핑한 `useSuspendedQuery` 훅 추가 (https://github.com/woowacourse-teams/2022-moamoa/blob/develop/frontend/src/hooks/useSuspendedQuery.ts)
* `assert` 함수를 사용하여 타입 narrowing (https://github.com/elecdeer/yumeshop-frontend/pull/11/files#diff-5148bf08c39bd344867662810fd1ab19be7fd52a039c0988786bd0add1ce0c94R9)

## 🎸 기타사항
연관 레퍼런스
* TanStack Query 관련 이슈: https://github.com/TanStack/query/issues/1297
* Toss Slash 라이브러리의 `useSuspendedQuery`: https://github.com/toss/slash/blob/main/packages/react/react-query/src/hooks/useSuspendedQuery.ts

**Comment by sh981013s** [comment]
꼭 필요했었는데 너무 좋아요!
