### ISSUE TITLE
메뉴, 메뉴판 이미지 cloudFront prefix 수정

### ISSUE THREAD

**Issue by green-kong** [woowacourse-teams/2023-yozm-cafe#397]
## 📑 작업 사항

> menu, menuBoard imageUrl prefix 수정

## 📝 에러 내용

> 메뉴,메뉴판 이미지 엑박으로 뜸

## 👾 에러 원인

> 이미지 url prefix가 붙어있지 않음

## 🎸 기타 사항

> 기타 사항을 작성해주세요

**Comment by solo5star** [comment]
풀스택 아저씨 감사합니다 🥹
