### ISSUE TITLE
React Fast Refresh 적용

### ISSUE THREAD

**Issue by solo5star** [woowacourse-teams/2023-yozm-cafe#42]
## 📑 논의 사항
* 현재 webpack dev server에서는 react fast refresh가 동작하지 않습니다.
* 소스 코드를 편집하고 저장하였을 때 페이지 refresh가 발생합니다.
* 페이지 refresh 없이 변경된 코드가 반영되도록 하는 fast refresh를 적용하는 것을 제안합니다.

## 📑 참고 자료
* 관련 이슈: https://github.com/facebook/react/issues/16604
* react-refresh-webpack-plugin: https://github.com/pmmmwh/react-refresh-webpack-plugin

**Comment by jeongwusi** [comment]
fast refresh의 경우 수시로 반영이 되고 잘못 입력한 경우 바로 에러가 나와서 저는 불편하다고 느끼는데요...!

**Comment by solo5star** [comment]
좀 더 개발해보고 불편하면 이에 대해 생각해봅시다

**Comment by jeongwusi** [comment]
구웃

**Comment by solo5star** [comment]
하드 리프레시로 인해 디버깅 시간이 길어지고 있습니다. 따라서 이슈를 다시 open 하였습니다.
